spring:
    config:
      activate:
          on-profile: real
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    session:
        store-type: jdbc
